INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Mr. Chocolate", 21, "M", "Blue", "Angry", 2)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Rowdy", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Tabitha", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Sergeant Brown", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Melissa", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Rowdy", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Grinch", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES ("Wendy", 23, "F", "Brown", "Calm", 1)
INSERT INTO bears VALUES (name, age, sex, color,temperament, alive) VALUES (NULL, 23, "F", "Brown", "Calm", 1)

