INSERT INTO bears VALUES (name,)
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES
INSERT INTO bears VALUES